channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13               # https://pyreadiness.org/3.9/ 

  - pip=22.3                    # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==19.0.0    # https://rpaframework.org/releasenotes.html

variables:
  EMAIL_ADDRESS: xxx@gmail.com        # Add here your email address or leave it empty
  SOCIAL_SECURITY_NUMBER: yyyymmdd-xxxx   # Add here your social security number or leave it empty
